# Generated by Django 4.2.7 on 2025-11-15 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_likeq_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='likea',
            name='value',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1),
        ),
        migrations.AddField(
            model_name='likeq',
            name='value',
            field=models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], default=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.question'),
        ),
        migrations.AlterField(
            model_name='likea',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.answer'),
        ),
        migrations.AlterField(
            model_name='likeq',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app.question'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
